93 locales passing, 17 aren't

diff --git a/update_test_data b/update_test_data
--- a/update_test_data
+++ b/update_test_data
@@ -3,7 +3,7 @@
 
 # The location of the `ex_cldr_person_names` repo
 export EX_CLDR_PERSON_NAMES="${EX_CLDR_PERSON_NAMES:=$HOME/Development/cldr_person_names}"
-[ ! -d $EX_CLDR_PERSON_NAMES ] && { echo "ex_cldr_person_names repository $EX_CLDR_UNIT was not found."; exit 1; }
+[ ! -d $EX_CLDR_PERSON_NAMES ] && { echo "ex_cldr_person_names repository $EX_CLDR_PERSON_NAMES was not found."; exit 1; }
 
 # The location of the cloned CLDR repo
 export CLDR_REPO="${CLDR_REPO:=$HOME/Development/cldr_repo}"
